#ifndef EXCELLENTEAM_EREZ_C_DNA_ANALYZER_OMAIRINO_CONTROLLER_H
#define EXCELLENTEAM_EREZ_C_DNA_ANALYZER_OMAIRINO_CONTROLLER_H


class Controller {

};


#endif //EXCELLENTEAM_EREZ_C_DNA_ANALYZER_OMAIRINO_CONTROLLER_H
