//
// Created by Administrator on 12/26/2018.
//

#ifndef EXCELLENTEAM_EREZ_C_DNA_ANALYZER_OMAIRINO_CLI_H
#define EXCELLENTEAM_EREZ_C_DNA_ANALYZER_OMAIRINO_CLI_H


class CLI {

};


#endif //EXCELLENTEAM_EREZ_C_DNA_ANALYZER_OMAIRINO_CLI_H
